// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUA7wSVmb0mwKWTRqcBQjviULZg_Iu9zw',
    appId: '1:154615027826:web:2b3884e8d582c612f24aeb',
    messagingSenderId: '154615027826',
    projectId: 'urbanfix-99895',
    authDomain: 'urbanfix-99895.firebaseapp.com',
    storageBucket: 'urbanfix-99895.firebasestorage.app',
    measurementId: 'G-TC34Y75PW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwUJ_GxAARikmmdbXuiK4WQiSiM5LYVJ4',
    appId: '1:154615027826:android:3bf7a59e41af3221f24aeb',
    messagingSenderId: '154615027826',
    projectId: 'urbanfix-99895',
    storageBucket: 'urbanfix-99895.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1ZSliKJ5xxdvWTQ9mAHPO3dKmrZUVdBk',
    appId: '1:154615027826:ios:fcfe4d8b88ecb480f24aeb',
    messagingSenderId: '154615027826',
    projectId: 'urbanfix-99895',
    storageBucket: 'urbanfix-99895.firebasestorage.app',
    iosBundleId: 'com.example.urbanfix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1ZSliKJ5xxdvWTQ9mAHPO3dKmrZUVdBk',
    appId: '1:154615027826:ios:fcfe4d8b88ecb480f24aeb',
    messagingSenderId: '154615027826',
    projectId: 'urbanfix-99895',
    storageBucket: 'urbanfix-99895.firebasestorage.app',
    iosBundleId: 'com.example.urbanfix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUA7wSVmb0mwKWTRqcBQjviULZg_Iu9zw',
    appId: '1:154615027826:web:439601f1bbaaf17cf24aeb',
    messagingSenderId: '154615027826',
    projectId: 'urbanfix-99895',
    authDomain: 'urbanfix-99895.firebaseapp.com',
    storageBucket: 'urbanfix-99895.firebasestorage.app',
    measurementId: 'G-F3FVRQBK8N',
  );
}
